---
default_stages: [commit]
exclude: vale/styles/*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=no]
      - id: check-added-large-files
        args: [--maxkb=10240]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        name: Prettier

  - repo: local
    hooks:
      - id: dockerfile-provides-entrypoint
        name: Vale
        language: docker_image
        entry: jdkato/vale:latest

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.2.0
    hooks:
      - id: eslint
        name: ESLint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - jest@27.0.2
          - eslint@8.1.0
          - typescript@4.4.4
          - eslint-config-prettier@8.3.0
          - eslint-config-standard@16.0.3
          - eslint-plugin-import@2.25.2
          - eslint-plugin-jest@25.2.2
          - eslint-plugin-node@11.1.0
          - eslint-plugin-promise@5.1.1
          - eslint-plugin-tsdoc@0.2.14
          - "@typescript-eslint/eslint-plugin@5.2.0"
          - "@typescript-eslint/parser@5.2.0"
